### ISSUE TITLE
Chapter3: posterior_grid_approx function

### ISSUE THREAD

**Issue by sushmit86** [pymc-devs/resources#92]
Should the function posterior_grid_approx have the prior as

`prior = np.repeat(1, grid_points)  # uniform`
The solution has the prior as

`prior = np.repeat(5, grid_points)  # uniform`

**Comment by aloctavodia** [comment]
The actual value does not matter, if you compute the posterior as proportional to the likelihood * prior, you will be changing the constant of proportionality, but the relative posterior values will be the same. If instead you normalize the posterior, then the normalization will take into account the 1 or 5 factor. 

If you really want the prior to be a valid pmf then instead of 1 it should be np.repeat(1/grid_points, grid_points), so the sum will be 1.



1/grid_points

**Comment by canyon289** [comment]
@sushmit86 I mean this in the kindest way. Try changing the value in the code and see what happens :)

**Comment by sushmit86** [comment]
Thanks so much. I had thought so the prior should not matter

**Comment by jdw8** [comment]
I think the problem is not with does it work, but that a prior is a probability distribution which should have an area under the curve of 1 and not 5.
